---
# nfs-utils was installed on other nodes but not these yet
- name: Make sure they have the right pkgs 
  hosts: all
  become: yes
  tasks:
  - name: Install nfs and semanage packages  
    dnf:
      name:
        - nfs-utils
      state: present

- name: Setup a shared logging folder on db
  hosts: db
  become: yes
  tasks:
  - name: Creating that folder
    file:
      path: /share/logs
      state: directory
      mode: '0777'

  - name: Enter it into /etc/exports
    lineinfile:
      path: /etc/exports
      line: '/share/logs *(rw,sync,no_root_squash)'

  - name: Export it
    command: exportfs -ra

# Create the dir to mount the nfs share
- name: Client logging setup/mounting the nfs share
  hosts: all
  become: yes
  tasks:
  - name: Create mount point
    file: 
      path: /var/log/remote
      state: directory

  - name: Mount the share from db
    mount:
      path: /var/log/remote
      src: "db:/share/logs"
      fstype: nfs
      opts: 'defaults,context="system_u:object_r:var_log_t:s0"'
      state: mounted
    when: inventory_hostname != 'db'
   

# Make sure rsyslog on all hosts logs to the nfs share mount
  - name: Rsyslog needs to stream logs across the network to db
    lineinfile:
      path: /etc/rsyslog.conf
      regexp: '^\*\.\*\s+.*'
      line: "*.* /var/log/remote/{{ inventory_hostname }}.log"
      
  - name: Restart rsyslog
    service:
      name: rsyslog
      state: restarted