---
- name: Prepare the webservers
  hosts: webservers
  become: yes
  tasks:
    - name: Install nfs-utils
      dnf:
        name: nfs-utils
        state: present

    - name: Install nginx
      dnf:
        name: nginx
        state: present

    - name: Start and enable nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Mount the db share to var/www/html
      ansible.posix.mount:
        src: db:/share/nfs
        path: /var/www/html
        opts: rw,sync
        state: mounted
        fstype: nfs

    - name: Open the firewall for http traffic
      firewalld:
        service: http
        permanent: yes
        immediate: yes
        state: enabled


